name: Build TIBCO EMS Client (.NET Core 3.1)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/TIBCO EMS Client
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/TIBCO EMS Client
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/TIBCO EMS Client
